name: Deploy static website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'assets/**'       # 监控 assets 目录下的所有文件
      - 'content/**'
      - 'template/**'
      - '.github/**'
      - 'src/**'
      - 'config.toml'

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # 使用的 Go 版本

      - name: Run Go program
        run: go run ./src/  # 运行你的 Go 程序

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./output  # 静态文件的目录

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          publish_dir: ./output  # 静态文件的目录
#          github_token: ${{ secrets.GITHUB_TOKEN }}
##          publish_branch: gh-pages  # 发布到 gh-pages 分支
