name: Deploy static website to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'assets/**'       # 监控 assets 目录下的所有文件
      - 'content/**'
      - 'template/**'
      - '.github/**'
      - 'src/**'
      - 'config.toml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # 使用的 Go 版本

      - name: Run Go program
        run: go run ./src/  # 运行你的 Go 程序

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./output  # 静态文件的目录
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages  # 发布到 gh-pages 分支